Update staging-backend.yml

diff --git a/.github/workflows/staging-backend.yml b/.github/workflows/staging-backend.yml
--- a/.github/workflows/staging-backend.yml
+++ b/.github/workflows/staging-backend.yml
@@ -67,10 +67,15 @@ jobs:
         with:
           name: code-coverage
           path: ./backend/coverage.txt # Make sure to use the same file name you chose for the "-coverprofile" in the "Test" step
-      - name: code coverage
+      - name: Check Code Coverage
         run: |
           cd ./backend
-          go tool cover -func=coverage.txt | grep total | awk '{print $3}'
+          coverage=$(go tool cover -func=coverage.txt | grep total | awk '{print $3}' | sed 's/%//')
+          echo "Code Coverage: $coverage%"
+          if (( $(echo "$coverage < 80" | bc -l) )); then
+            echo "Code coverage is below 80%. Failing the job."
+            exit 1
+          fi
 
   code_coverage:
     name: "Code coverage report"
